### ISSUE TITLE
feature request：support VoLTE

### ISSUE THREAD

**Issue by ivysrono** [YadavMohit19/Releases#1]
Arrow-v12.1-xaga-UNOFFICIAL-20221108-VANILLA don't support VoLTE, while https://github.com/wbs306/device_xiaomi_xaga support it.

**Comment by YadavMohit19** [comment]
first check your all settings, volte works seamless

**Comment by ivysrono** [comment]
Test again:
It does not work at first.
Turn off then turn on, it works.

Thanks.
