### ISSUE TITLE
feature request: provide TWRP recovery

### ISSUE THREAD

**Issue by ivysrono** [YadavMohit19/Releases#3]
Xaga has no public stable TWRP recovery now. So it's hard to flash third party system.

Would you provide your recovery?

Or provide system image which we can flash by fastboot.

**Comment by DeepBlueBubble** [comment]
https://github.com/wbs306/device_xiaomi_xaga-TWRP

Use this and adb sideload rom
(Don't swap slot in this TWRP)
Only use the TWRP on kernel version 5.10.66.

**Comment by ivysrono** [comment]
我说现在的TWRP不稳定，其实也就是指这个。毕竟wbs306有自己的rom，而我试了用他的TWRP刷这里的rom后，至少出现以下困惑：
1.无法直接重启进入recovery。`adb reboot recovery` 会进入xiaomi自带的recovery或者报错，得从fastboot重启进入recovery。
2.更新或者更换系统困难。从miui刷成别的系统容易，但要第二次进入更新或者想要更换别的rom，wbs 的 TWRP 常常报错：
```
挂载"/vendor"失败（Invalid argument）
无法挂载/data/media/TWRP/.twrps
挂载"/data"失败（Invalid argument）
```
3.进入recovery困难。多次需要 `fastboot -w` 才能进入 TWRP。

也不清楚是我操作有问题还是什么，所以我说现有TWRP不稳定，想看看作者用的是什么，或者就直接通过fastboot刷镜像，就像刷GSI一样，反而安全不容易挂。

**Comment by DeepBlueBubble** [comment]
好吧...那我确实是不知道该怎么做了....

**Comment by ivysrono** [comment]
怎么也想不到GSI会有电话没有声音的问题，早知道就不买这机了
